services:
  user-service:
    image: 272183979798.dkr.ecr.us-east-1.amazonaws.com/shopflow-user-service:latest
    ports:
      - "8001:8001"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  product-service:
    image: 272183979798.dkr.ecr.us-east-1.amazonaws.com/shopflow-product-service:latest
    ports:
      - "8010:8002"

  order-service:
    image: 272183979798.dkr.ecr.us-east-1.amazonaws.com/shopflow-order-service:latest
    ports:
      - "8015:8003"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_SERVICE_URL: http://user-service:8001
      PRODUCT_SERVICE_URL: http://product-service:8002
    depends_on:
      - user-service
      - product-service

  flyway:
    image: flyway/flyway:latest
    command: >
      -url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      -user=${DB_USER}
      -password=${DB_PASSWORD}
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./db/migration:/flyway/sql
    restart: "no"    

  flyway-seed:
    image: flyway/flyway:latest
    command: >
      -url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      -user=${DB_USER}
      -password=${DB_PASSWORD}
      -locations=filesystem:/flyway/sql
      -table=flyway_seed_history
      migrate
    volumes:
      - ./db/seed:/flyway/sql
    restart: "no"  