server.port=8003
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:shopflow}
spring.datasource.username=${DB_USER:shopflowuser}
spring.datasource.password=${DB_PASSWORD:shopflowpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

services.user-service-url=${USER_SERVICE_URL:http://user-service:8001}
services.product-service-url=${PRODUCT_SERVICE_URL:http://product-service:8002}