name: Deploy ShopFlow

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 272183979798.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Order Service
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 272183979798.dkr.ecr.us-east-1.amazonaws.com/shopflow-order-service:latest \
            ./services/order-service \
            --push